name: run-tests

on:
    push:
        branches: [main]
    pull_request:
    schedule:
        - cron: "0 0 * * *"

jobs:
    test:
        if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]
                php: [8.4, 8.3]
                laravel: ["^13.0", "^12.0", "^11.0"]
                dependency-version: [prefer-stable]
        name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }} - ${{ matrix.os }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v6

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, intl, fileinfo
                  coverage: none

            - name: Setup problem matchers
              run: |
                  echo "::add-matcher::${{ runner.tool_cache }}/php.json"
                  echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

            - name: Install dependencies
              run: |
                  composer require "laravel/framework:${{ matrix.laravel }}" --dev --no-interaction --no-update
                  composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-progress

            - name: Execute tests
              run: vendor/bin/pest
